name: Keep Webpage Alive

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          sudo ln -s /usr/bin/chromedriver /usr/local/bin/chromedriver
          pip install selenium

      - name: Run Selenium script
        shell: bash
        run: |
          python3 - <<EOF
          import time
          from selenium import webdriver
          from selenium.webdriver.chrome.options import Options

          options = Options()
          options.add_argument("--headless")
          options.add_argument("--no-sandbox")
          options.add_argument("--disable-dev-shm-usage")
          options.binary_location = "/usr/bin/chromium-browser"

          driver = webdriver.Chrome(executable_path="/usr/bin/chromedriver", options=options)
          driver.get("http://intergrant.streamlit.app/")
          print("Webpage opened successfully. Waiting for 3 minutes...")
          time.sleep(180)
          driver.quit()
          print("Done.")
          EOF
